services:
  1icnb2t14y:
    container_name: 1icnb2t14y_app
    image: ghcr.io/mr-devloper005/webinfinityhub.com:latest
    env_file:
      - .env
    network_mode: bridge
    restart: always
    ports:
      - "127.0.0.1:3215:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5m
      timeout: 3s
      retries: 2
